FROM golang:latest

WORKDIR /go/src/app
COPY go/src/app .
RUN go-wrapper download   # "go get -d -v ./..."
RUN go-wrapper install    # "go install -v ./..."
EXPOSE 80
CMD ["go-wrapper", "run"] # ["app"]