FROM lightstep/envoydemo:latest

RUN apt-get update && \
    apt-get install -qqy \
	ca-certificates
COPY envoy-front.json /etc/envoy.json
COPY ls_access_token /etc/ls_access_token
EXPOSE 80
EXPOSE 8001
CMD envoy -c /etc/envoy.json --service-cluster front-proxy --service-node `hostname`