version: '2'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    networks:
      envoymesh:
        aliases:
          - front-envoy
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
    tty: true

  donutsalon-1:
    image: donutz/donutbin
    networks:
      envoymesh:
        aliases:
          - donutsalon-1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
      - "8080"
    ports:
      - "80"
      - "8080"

  donutsalon-2:
    image: donutz/donutbin
    networks:
      envoymesh:
        aliases:
          - donutsalon-2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
      - "8080"
    ports:
      - "80"
      - "8080"
  
  donutsalon-3:
    image: donutz/donutbin
    networks:
      envoymesh:
        aliases:
          - donutsalon-3
    environment:
      - SERVICE_NAME=3
    expose:
      - "80"
      - "8080"
    ports:
      - "80"
      - "8080"

  spire-server:
    build: 
      context: ./spire
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - spire-server
    expose:
      - "8080"
      - "8081"
    ports:
      - "8080:8080"
      - "8082:8081"
    tty: true

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      envoymesh:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
      - "5775"
      - "6831"
      - "6832"
      - "5778"
      - "14268"
 
    ports:
      - "9411:9411"
      - "16687:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"

  prometheus:
    image: quay.io/prometheus/prometheus
    networks:
      envoymesh:
        aliases:
          - prometheus
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    
networks:
  envoymesh: {}
