version: '2'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    networks:
      envoymesh:
        aliases:
          - front-envoy
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
    tty: true

  donutsalon-1:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    networks:
      envoymesh:
        aliases:
          - donutsalon-1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
      - "8080"
    ports:
      - "9001:80"
      - "8081:8080"

  spire-server:
    build: 
      context: ./spire
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - spire-server
    expose:
      - "8080"
      - "8081"
    ports:
      - "8080:8080"
      - "8082:8081"
    tty: true

  jaeger:
    image: jaegertracing/all-in-one
    networks:
      envoymesh:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

networks:
  envoymesh: {}
