route:
 group_by: [cluster]
 receiver: slack

receivers:
- name: slack
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '@sabree'